# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6f070727ab29ffd4e1627d7f8a284a7fac8cebdc76afe2e9241ad6ff91a0d02635e618725a1a9601f6b5da76674d7a26b4601944d1c56805a4f75c2e3e6bf0d

test:
  secret_key_base: 93ed36dfac39a712d0f8395eaa96f58df56640c916e78d5a9edff954a970a50f07ff57ae881fe6c9c44ff4afc48b8233aa29faf2628aca3225a1812e9b165175

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
